config/routes.rb
Rails.application.routes.draw do

  root to: 'homepage#index'
  get 'auth/:provider/callback', to: 'sessions#create'

  resources :homepage, only: [:index]
  resources :dashboard, only: [:index]
  resources :users
  resources :user_followees, except: [:edit, :update, :new]
  resources :suggested_followees, only: [:index]
  resources :books, only: [:index]
  resources :sessions, only: [:create]

  get '/login',  to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :book_search_results, only: [:index]

  post '/add-book', to: 'book_on_shelf#create'

  resources :book_comparisons, only: [:show]

end

app/models/suggested_followee.rb
class SuggestedFollowee < ActiveRecord::Base
  belongs_to :followee
  belongs_to :user

  def reason_for_suggestion
    "Followed by #{followee.name}"
  end
end

app/controllers/suggested_followees_controller.rb
class SuggestedFolloweesController < ApplicationController

  def index
    @suggested_followees = current_user.suggested_followees
  end

end

app/views/suggested_followees/_suggested_followee.html.erb
<div class="panel clearfix">
  <div>

    <div class="row">
      <div class="small-10 columns small-offset-1 followee-name-container">
        <h5 class="text-center followee-name"><%= suggested_followee.name %></h5>
      </div>
    </div>

    <div class="row" id="reason-for-user-suggestion" >
      <p class=text-center><%= suggested_followee.reason_for_suggestion %></p>
    </div>
    <div class="container">
      <div class="followee-image-container small-10 columns small-offset-1">
        <%= image_tag suggested_followee.image_url, class: 'panel-image', lazy: true %>
      </div>
      <div class="row">
        <div class="small-8 columns small-offset-2 text-center">
          <%= link_to "follow", user_followees_path(followee_id: suggested_followee.goodreads_id), method: :post, class: 'bold-link left' %>
          <span>|</span>
          <%= link_to "compare", book_comparison_path(id: suggested_followee.goodreads_id), class: 'bold-link right' %>
        </div>
      </div>
      <div class="row">
        <div class="small-6 columns small-offset-2 right">
        </div>
      </div>
    </div>


  </div>
</div>

app/views/suggested_followees/index.html.erb
<div class="row">
  <div class="small-8 columns small-offset-2 page-title">
    <h2 class="text-center">People you should follow</h2>
  </div>
</div>

<div class="row" id="book-grid">
  <ul class="medium-block-grid-4">
    <% @suggested_followees.each do |suggested_followee| %>
      <li><%= render partial: 'suggested_followee', locals: {suggested_followee: suggested_followee} %></li>
    <% end %>
  </ul>
</div>