config/routes.rb
Rails.application.routes.draw do

  root to: 'homepage#index'
  get 'auth/:provider/callback', to: 'sessions#create'

  resources :homepage, only: [:index]
  resources :dashboard, only: [:index]
  resources :users
  resources :user_followees, except: [:edit, :update, :new]
  resources :suggested_followees, only: [:index]
  resources :books, only: [:index]
  resources :sessions, only: [:create]

  get '/login',  to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :book_search_results, only: [:index]

  post '/add-book', to: 'book_on_shelf#create'

  resources :book_comparisons, only: [:show]

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :goodreads_id, uniqueness: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = current_user.books.paginate(:page => params[:page])
  end
end

app/views/books/_book.html.erb
<div class="panel clearfix">
    <div class="row text-center">
      <h5 id="book-title"><b><%= book.title %></b></h5>
    </div>

    <div class="row">
      <div id="book-image" class="small-6 columns left">
        <%= image_tag book.image_url %>
      </div>
      <div id="panel-scores" class="small-6 columns left" style="float: right">
        <h6 class="scores">goodreads score: <br/></h6>
        <h6><b><%= book.goodreads_rating %></b></h6>
        <h6 class="scores">reviewer score:</h6>
        <h6><b><%= custom_rating(book) %></b></h6>
        <div id="gr_add_to_books">
          <div>
            <%= link_to 'add to "to-read"', add_book_path(book_goodreads_id: book.goodreads_id), method: :post, class: 'bold-link' %>
          </div>
        </div>
      </div>
    </div>

</div>

app/views/books/index.html.erb
<div class="row">
  <div class="small-8 columns small-offset-2 page-title">
    <h2 class="text-center">Books with Reviewer ratings</h2>
  </div>
</div>

<div class="container">
  <div class="small-6 columns small-offset-3 pagination-widget">
    <%= will_paginate @books, renderer: FoundationPagination::Rails %>
  </div>
</div>

<div class="row" id="book-grid">
  <ul class="medium-block-grid-3">
    <% @books.each do |book| %>
      <li><%= render partial: 'book', locals: {book: book} %></li>
    <% end %>
  </ul>
</div>


<div class="container">
  <div class="small-6 columns small-offset-3 pagination-widget">
    <%= will_paginate @books, renderer: FoundationPagination::Rails %>
  </div>
</div>