config/routes.rb
Rails.application.routes.draw do

  root to: 'homepage#index'
  get 'auth/:provider/callback', to: 'sessions#create'

  resources :homepage, only: [:index]
  resources :dashboard, only: [:index]
  resources :users
  resources :user_followees, except: [:edit, :update, :new]
  resources :suggested_followees, only: [:index]
  resources :books, only: [:index]
  resources :sessions, only: [:create]

  get '/login',  to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :book_search_results, only: [:index]

  post '/add-book', to: 'book_on_shelf#create'

  resources :book_comparisons, only: [:show]

end

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <% unless request.fullpath == root_path %>
        <h1><%= link_to 'Reviewer', root_path %></h1>
      <% end %>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <% if current_user %>
        <li><%= link_to "logout", logout_path %></li>
      <% elsif request.fullpath != root_path %>
        <li><%= link_to image_tag("goodreads-login-button.png"), login_path %></li>
      <% end %>
      <li class="has-dropdown">
        <a href="#" id="actions-button">Actions</a>
        <ul class="dropdown">
          <li class ="dropdown-link"><%= link_to "User Dashboard", dashboard_index_path %></li>
          <li class ="dropdown-link"><%= link_to "Rated Books", books_path %></li>
          <li class ="dropdown-link"><%= link_to "People you're following", user_followees_path %></li>
          <li class ="dropdown-link"><%= link_to "People you should follow", suggested_followees_path%></li>
        </ul>
      </li>
    </ul>
  </section>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Reviewer" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render partial: 'layouts/nav' %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>